title: 
  en: Hero Banner
  fr: Bannière d'en-tête
label:
  en: Hero
  fr: En-tête
description: 
  en: Special section to be used as a hero banner. Creates a full-width section with a background image and text.
  fr: Section spéciale à utiliser comme bannière d'en-tête. Crée une section pleine largeur avec une image d'arrière-plan et du texte.

category: hero
export: true

elements:
  banner:
  title:
  subtitle:
  link:
    description: 
      en: One or two links that put under the text content.
      fr: Un ou deux liens qui sont placés sous le contenu textuel.

properties:
  height:
    label: 
      en: Height
      fr: Hauteur
    type: string
    default: 100vh
    enum:
      - label: 
          en: 100% Screen Height
          fr: 100% de la hauteur de l'écran
        value: 100vh
      - label: 
          en: 80% Screen Height
          fr: 80% de la hauteur de l'écran
        value: 80vh
      - label: 
          en: 60% Screen Height
          fr: 60% de la hauteur de l'écran
        value: 60vh
      - label: 
          en: 40% Screen Height
          fr: 40% de la hauteur de l'écran
        value: 40vh
    description: 
      en: The height of the hero section.
      fr: La hauteur de la section d'en-tête.
  alignment:
    label: 
      en: Content Alignment
      fr: Alignement du contenu
    type: string
    default: left
    enum:
      - label: 
          en: Left
          fr: Gauche
        value: left
      - label: 
          en: Center
          fr: Centre
        value: center
      - label: 
          en: Right
          fr: Droite
        value: right
    description: 
      en: The alignment of the content in the hero section.
      fr: L'alignement du contenu dans la section d'en-tête.

presets:
  full_left:
    label:
      en: Full-height hero banner with content on the left.
      fr: Bannière d'en-tête pleine hauteur avec contenu à gauche.
    properties:
      height: 100vh
      alignment: left
    image: full_left.png