title:
  en: Side Navigation Page
  fr: Page de navigation latérale
label:
  en: Side Navigation Page
  fr: Page de navigation latérale
description:
  en: A versatile page component that combines layout and content rendering. It displays the main content on the left and a navigation list on the right, allowing users to easily explore different sections of the page.
  fr: Un composant de page polyvalent qui combine la mise en page et le rendu du contenu. Il affiche le contenu principal à gauche et une liste de navigation à droite, permettant aux utilisateurs d'explorer facilement différentes sections de la page.

category: page
export: true

elements:
  title:
  subtitle:

items:
  separator: section
  elements:
    title:
    properties:
      label:
        en: JSON Properties
        fr: Propriétés JSON
      description:
        en: JSON properties for each List Item subsection, required properties are 'component' (choose from 'simple_card', 'news', 'details', 'assets' and 'contact') and 'id' (unique identifier).
        fr: Propriétés JSON pour chaque sous-section Élément de liste, les propriétés requises sont 'component' (choisir parmi 'simple_card', 'news', 'details', 'assets' et 'contact') et 'id' (identifiant unique).
    _raw: 
      en: |
        <i style='color: #6b7280;'>List item with different component will need different type of content</i>

images:
  - example.png