title:
  en: Template Catalog
  fr: Catalogue de modèles
label:
  en: Template Catalog
  fr: Catalogue de modèles
description:
  en: A versatile component that displays a collection of website templates with search, filter, and sort functionality. Each template includes the title, a cover image and a preview video for an engaging browsing experience.
  fr: Un composant polyvalent qui affiche une collection de modèles de site Web avec des fonctionnalités de recherche, de filtrage et de tri. Chaque modèle comprend le titre, une image de couverture et une vidéo de prévisualisation pour une expérience de navigation engageante.

category: template
export: true

elements:
  properties:
    label:
      en: JSON Properties
      fr: Propriétés JSON
    description:
      en: The JSON properties as configuration for the template catalog, required properties are 'search_box', 'info', 'filters' and 'sort'.
      fr: Les propriétés JSON comme configuration pour le catalogue de modèles, les propriétés requises sont 'search_box', 'info', 'filters' et 'sort'.

images:
  - example.png