title: 
  en: Feature Cards
  fr: Fonctionnalités en carte
label:
  en: Features - Card
  fr: Fonctionnalités - Carte
description: 
  en: Special section only to be used in the header page. Creates a navigation bar with automatic links to all website pages.
  fr: Section spéciale à utiliser uniquement dans la page d'en-tête. Crée une barre de navigation avec des liens automatiques vers toutes les pages du site web.

