title: 
  en: Feature Cards
  fr: Fonctionnalités en carte
label:
  en: Features - Card
  fr: Fonctionnalités - Carte
description: 
  en: Section showcasing a collection of features or services in a card format, layout can be horizontal scroll list or grid.
  fr: Section mettant en avant une collection de fonctionnalités ou de services sous forme de cartes, la mise en page peut être une liste de défilement horizontale ou une grille.

category: feature
export: true

properties:
  layout:
    label: 
      en: Layout
      fr: Mise en page
    type: string
    default: scroll
    enum:
      - label: 
          en: Horizontal Scroll List
          fr: Liste de défilement horizontale
        value: scroll
      - label: 
          en: Grid
          fr: Grille
        value: grid
    description:
      en: The layout of the feature cards.
      fr: La mise en page des cartes de fonctionnalités.
  cardStyle:
    label: 
      en: Card Style
      fr: Style de carte
    type: string
    default: compact
    enum:
      - label:
          en: Compact
          fr: Compact
        value: compact
      - label:
          en: Expanded
          fr: Étendu
        value: expanded
      - label:
          en: Overlay
          fr: Superposition
        value: overlay
    description:
      en: The style of the feature cards.
      fr: Le style des cartes de fonctionnalités.