name: Academic Series 1
description: A collection of components for building academic websites.
page_templates:
  - name: About
    components:
      - name: Block
        preset: centered_tight
      - name: List
        preset: medium
categories:
  content:
    label:
      en: Content
      fr: Contenu
    description:
      en: Components that display content.
      fr: Composants qui affichent du contenu.
  form:
    label:
      en: Form
      fr: Formulaire
    description:
      en: Components that allow users to input data.
      fr: Composants qui permettent aux utilisateurs de saisir des données.
version: preset
