title: 
  en: Term Definitions
  fr: Définitions des termes
label:
  en: Glossary
  fr: Glossaire
description:
  en: A section to briefly explain a set of terms.
  fr: Une section pour expliquer brièvement un ensemble de termes.

category: content
export: true

elements:
  title:
  subtitle:

items:
  separator: divider
  elements:
    title:
      description:
        en: The term to be defined.
        fr: Le terme à définir.
    text:
      description:
        en: The definition of the term.
        fr: La définition du terme.
    icon:
      type: icon
      description: 
        en: An icon to visually represent the term.
        fr: Une icône pour représenter visuellement le terme.
   
images:
  - example.png
