title: 
  en: Media Broadcast
  fr: Diffusion de médias
label:
  en: Media Broadcast
  fr: Diffusion de médias
description: 
  en: A section designed to showcase a collection of media content such as social links, images or videos. Perfect for displaying a gallery of media content or broadcasting a series of videos or podcasts.
  fr: Une section conçue pour mettre en avant une collection de contenus médias tels que des liens sociaux, des images ou des vidéos. Parfait pour afficher une galerie de contenus médias ou diffuser une série de vidéos ou de podcasts.

category: content
export: true