title: 
  en: Header
  fr: En-tête
label:
  en: Header
  fr: En-tête
description: 
  en: Special section only to be used in the header page. Creates a navigation bar with automatic links to all website pages.
  fr: Section spéciale à utiliser uniquement dans la page d'en-tête. Crée une barre de navigation avec des liens automatiques vers toutes les pages du site web.

category: header
export: true

elements:
  icon:
    title: 
      en: Logo
      fr: Logo
    description:
      en: The logo image to display in the header.
      fr: L'image du logo à afficher dans l'en-tête.
  list:
    type: list
    title: 
      en: Navigation Links
      fr: Liens de navigation
    description:
      en: The navigation links to display in the header, it is created as a list of links, each link can have children links.
      fr: Les liens de navigation à afficher dans l'en-tête, il est créé sous forme de liste de liens, chaque lien peut avoir des liens enfants.