title:
    en: Header
    fr: En-tête
label:
    en: Header
    fr: En-tête
description:
    en: The navigation header displays a logo, a list of navigation links, search bar, language switcher, and login/signup buttons.
    fr: L'en-tête de navigation affiche un logo, une liste de liens de navigation, une barre de recherche, un sélecteur de langue et des boutons de connexion/inscription.

category: header
export: true

elements:
    icon:
        title:
            en: Logo
            fr: Logo
        description:
            en: The logo image to display in the header.
            fr: L'image du logo à afficher dans l'en-tête.
    media:
        type: image
        description:
            en: The logo image to display in the header if icon is not set. Use the caption to set the correct image to use under different theme settings.
            fr: L'image du logo à afficher dans l'en-tête si l'icône n'est pas définie. Utilisez la légende pour définir l'image correcte à utiliser sous différents paramètres de thème.
    list:
        type: list
        title:
            en: Navigation Links
            fr: Liens de navigation
        description:
            en: The navigation links to display in the header, it is created as a list of links, each link can have children links. You can add a optional second list for account links such as login, signup, etc.
            fr: Les liens de navigation à afficher dans l'en-tête, ils sont créés sous forme de liste de liens, chaque lien peut avoir des liens enfants. Vous pouvez ajouter une deuxième liste facultative pour les liens de compte tels que la connexion, l'inscription, etc.

properties:
    login_url:
        label:
            en: Login URL
            fr: URL de connexion
        type: string
        description:
            en: The URL to the login page.
            fr: L'URL de la page de connexion.

images:
    - example.png
