title: 
  en: Pricing Features
  fr: Fonctionnalités de tarification
label:
  en: Pricing Features
  fr: Fonctionnalités de tarification
description:
  en: The pricing features section displays a list of features with their pricing.
  fr: La section des fonctionnalités de tarification affiche une liste de fonctionnalités avec leurs prix.

category: pricing
export: true

elements:
  title:
  subtitle:
  # list:
  #   description:
  #     en: The endnotes of the pricing features section.
  #     fr: Les notes de fin de la section des fonctionnalités de tarification.

items:
  separator: divider
  elements:
    icon:
      description:
        en: The icon of the feature.
        fr: L'icône de la fonctionnalité.
    title:
      description:
        en: The title of the feature.
        fr: Le titre de la fonctionnalité.
    list:
      description:
        en: Details of the feature in list format.
        fr: Détails de la fonctionnalité au format liste.

properties:
  appearance:
    label:
      en: Appearance
      fr: Apparence
    type: string
    default: subtle
    enum:
      - label:
          en: Subtle
          fr: Subtil
        value: subtle
      - label:
          en: Fancy
          fr: Fantaisie
        value: fancy
    description:
      en: The appearance of the pricing tiers.
      fr: L'apparence des niveaux de tarification.
  appearance_preset:
    label:
      en: Appearance Preset
      fr: Préréglage d'apparence
    type: string
    default: none
    enum:
      - label:
          en: None
          fr: Aucun
        value: none
      - label:
          en: Ocean
          fr: Océan
        value: ocean
      - label:
          en: Ocean with box style
          fr: Océan avec style de boîte
        value: ocean-box
    description:
      en: The appearance preset of the pricing features when appearance is set to fancy. Choose none will use the Uniweb theme applied to this section.
      fr: Le préréglage d'apparence des fonctionnalités de tarification lorsque l'apparence est définie sur fantaisie. Choisir aucun utilisera le thème Uniweb appliqué à cette section.

images:
  - example.png