title: 
  en: Pricing Features
  fr: Fonctionnalités de tarification
label:
  en: Pricing Features
  fr: Fonctionnalités de tarification
description:
  en: The pricing features section displays a list of features with their pricing.
  fr: La section des fonctionnalités de tarification affiche une liste de fonctionnalités avec leurs prix.

category: pricing
export: true

elements:
  title:
  subtitle:
  list:
    description:
      en: The endnotes of the pricing features section.
      fr: Les notes de fin de la section des fonctionnalités de tarification.

items:
  separator: divider
  elements:
    icon:
      description:
        en: The icon of the feature.
        fr: L'icône de la fonctionnalité.
    title:
      description:
        en: The title of the feature.
        fr: Le titre de la fonctionnalité.
    subtitle:
      description:
        en: The subtitle of the feature.
        fr: Le sous-titre de la fonctionnalité.
    text:
      description:
        en: The text of the feature, if text has `|` it will be split into left and right.
        fr: Le texte de la fonctionnalité, si le texte a `|` il sera divisé en gauche et droite.

properties:
  color_tone:
    label:
      en: Color Tone
      fr: Tonalité de couleur
    type: string
    enum:
      - 
        label:
          en: Primary Color
          fr: Couleur principale
        value: primary
      - 
        label:
          en: Secondary Color
          fr: Couleur secondaire
        value: secondary
      - 
        label:
          en: None
          fr: Aucun
        value: none
    default: none
    description:
      en: The color tone of the pricing features section.
      fr: La tonalité de couleur de la section des fonctionnalités de tarification.

images:
  - example.png