title: 
  en: Video Hub
  fr: Hub de vidéos
label:
  en: Video Hub
  fr: Hub de vidéos
description: 
  en: A versatile and interactive component designed to display a collection of videos.
  fr: Un composant polyvalent et interactif conçu pour afficher une collection de vidéos

category: video
export: true

elements:
  title:
  subtitle:

images:
  - example.png

