title: 
  en: References Table
  fr: Tableau de références
label:
  en: References - Table
  fr: Références - Tableau
description: 
  en: Show references (APA) in table view with search, source configured in input widget.
  fr: Afficher les références (APA) en vue de tableau avec recherche, source configurée dans le widget d'entrée.

category: reference
export: true

input:
  type: reference
  limit: false

elements:
  title:

images:
  example:
    label:
      en: Example of showing references in table view.
      fr: Exemple d'affichage des références en vue de tableau.
    image: example.png
