title:
    en: Dynamic List
    fr: Liste dynamique
label:
    en: List - Dynamic
    fr: Liste - Dynamique
description:
    en: A component takes input of content profiles and displays them in a list, grid, or snapping card layout.
    fr: Un composant prend en entrée des profils de contenu et les affiche dans une liste, une grille ou une carte de défilement.

category: dynamic_content
export: true

input:
    type: any
    limit: false
    manualFormatting: true

elements:
    title:

items:
    separator: divider
    limit: 1
    manualFormattingOnly: true
    elements:
        background:
            title:
                en: Profile Banner
                fr: Bannière de profil
            description:
                en: The picture of the profile.
                fr: L'image du profil.
        title:
            description:
                en: The title of the profile.
                fr: Le titre du profil.
        subtitle:
            description:
                en: The subtitle of the profile.
                fr: Le sous-titre du profil.
        link:
            type: link
            description:
                en: One or more social media links that attach to the profile.
                fr: Un ou plusieurs liens de médias sociaux qui s'attachent au profil.

properties:
    layout:
        label:
            en: Layout
            fr: Mise en page
        type: string
        default: list
        enum:
            - label:
                  en: List
                  fr: Liste
              value: list
            - label:
                  en: Grid
                  fr: Grille
              value: grid
            - label:
                  en: Snapping Cards
                  fr: Cartes de défilement
              value: snapping
        description:
            en: The layout of the section.
            fr: La mise en page de la section.
    vertical_padding:
        label:
            en: Vertical Spacing
            fr: Espacement vertical
        type: string
        default: lg
        enum:
            - label:
                  en: Large
                  fr: Large
              value: lg
            - label:
                  en: Medium
                  fr: Moyen
              value: md
            - label:
                  en: Small
                  fr: Petit
              value: sm
            - label:
                  en: None
                  fr: Aucun
              value: none
        description:
            en: The space on top and bottom of the layout.
            fr: L'espace en haut et en bas de la mise en page.

presets:
    list:
        label:
            en: List Layout
            fr: Mise en page de la liste
        properties:
            layout: list
        image: list.png
    grid:
        label:
            en: Grid Layout
            fr: Mise en page de la grille
        properties:
            layout: grid
        image: grid.png
    snapping:
        label:
            en: Snapping Cards Layout
            fr: Mise en page de cartes de défilement
        properties:
            layout: snapping
        image: snapping.png
