title: 
  en: Left Panel
  fr: Panneau de gauche
label:
  en: Left Panel
  fr: Panneau de gauche
description:
  en: A component that render a list of navigation links, usually used for a sidebar.
  fr: Un composant qui rend une liste de liens de navigation, généralement utilisé pour une barre latérale.

export: true

images:
  - example.png