title: 
  en: Article List
  fr: Liste d'articles
label:
  en: Article List
  fr: Liste d'articles
description: 
  en: A component designed to display a collection of articles in a vertical list.
  fr: Un composant conçu pour afficher une collection d'articles dans une liste verticale.

category: article
export: true

elements:
  title:
  subtitle:

properties:
  width:  
    label:
      en: Content Width
      fr: Largeur du contenu
    type: string
    default: lg
    enum:
      - label:
          en: Small
          fr: Petit
        value: sm
      - label:
          en: Medium
          fr: Moyen
        value: md
      - label:
          en: Large
          fr: Large
        value: lg
      - label:
          en: Full Width
          fr: Pleine largeur
        value: full
    description:
      en: The width of the section.
      fr: La largeur de la section.
  vertical_padding:
    label:
      en: Vertical Spacing
      fr: Espacement vertical
    type: string
    default: lg
    enum:
      - label:
          en: Large
          fr: Large
        value: lg
      - label:
          en: Small
          fr: Petit
        value: sm
      - label:
          en: None
          fr: Aucun
        value: none
    description:
      en: The space on top and bottom of the layout.
      fr: L'espace en haut et en bas de la mise en page.
  horizontal_padding:
    label:
      en: Horizontal Spacing
      fr: Espacement horizontal
    type: string
    default: sm
    enum:
      - label:
          en: Large
          fr: Large
        value: lg
      - label:
          en: Small
          fr: Petit
        value: sm
      - label:
          en: None
          fr: Aucun
        value: none
    description:
      en: The space on the left and right of the layout.
      fr: L'espace à gauche et à droite de la mise en page.
  in_side_panel:
    label:
      en: In Side Panel
      fr: Dans le panneau latéral
    type: boolean
    default: false
    description:
      en: Indicates if the list is displayed in a side panel, if so, the gap in between content and text size will be adjusted accordingly.
      fr: Indique si la liste est affichée dans un panneau latéral, si c'est le cas, l'écart entre le contenu et la taille du texte sera ajusté en conséquence.

presets:
  side_list:
    label:
      en: List layout in side panel
      fr: Mise en page en liste dans un panneau latéral
    properties:
      width: full
      vertical_padding: lg
      horizontal_padding: sm
      in_side_panel: true
    image: side_list.png
