title: 
  en: Accent with Background image
  fr: Accent avec image de fond
label:
  en: Accent
  fr: Accent
description:
  en: This section calls attention to a specific block of text on the website by putting an image in the background.
  fr: Cette section attire l'attention sur un bloc de texte spécifique du site web en plaçant une image en arrière-plan.

category: content
export: true

elements:
  background:
  subtitle:
  text:
  link:

properties:
  alignment:
    label: 
      en: Content alignment
      fr: Alignement du contenu
    type: string
    enum:
      - label: 
          en: Left
          fr: Gauche
        value: left
      - label: 
          en: Center
          fr: Centre
        value: center
      - label: 
          en: Right
          fr: Droite
        value: right
    default: left
    description: 
      en: The alignment of the text content.
      fr: L'alignement du contenu texte.
  show_back_drop:
    label: 
      en: Text Backdrop
      fr: Toile de fond du texte
    type: boolean
    default: false
    description: 
      en: Whether or not the text will have a backdrop.
      fr: Si le texte aura ou non une toile de fond.

presets:
  right:
    label:
      en: Content on the Right
      fr: Contenu à droite
    properties:
      alignment: right
    image: right.png
  center:
    label:
      en: Content in the Center
      fr: Contenu au centre
    properties:
      alignment: center
    image: center.png
  left_backdrop:
    label:
      en: Content on the Left with Text Backdrop
      fr: Contenu à gauche avec toile de fond de texte
    properties:
      alignment: left
      show_back_drop: true
    image: left_backdrop.png