name: Marketing Series 1
description: A collection of components for building marketing websites.

page_templates:
  - name:
      en: Home Page
      fr: Page d'accueil
    page:
      en: Home
      fr: Accueil
    components:
      - name: Hero
      - name: FeatureSpotlight
      - name: FeatureCards
      - name: MediaBroadcast
      - name: ContentTeaser
  - name: 
      en: Blog Page
      fr: Page de blog
    page:
      en: Blog
      fr: Blog
    components:
      - name: HeroMedia
      - name: ArticleHub
  - name:
      en: Pricing Page
      fr: Page de tarification
    page:
      en: Pricing
      fr: Tarification
    components:
      - name: PricingHero
        preset: fancy_ocean
      - name: PricingTiers
        preset: fancy_ocean
      - name: PricingFeatures
        preset: fancy_ocean
      - name: FAQ
        preset: fancy_ocean
      - name: CallToAction
        preset: fancy_ocean