title: 
  en: Call to Action
  fr: Appel à l'action
label:
  en: Call to Action
  fr: Appel à l'action
description: 
  en: A section designed to encourage users to take a specific action such as signing up for a newsletter, downloading a resource, or contacting a sales representative. Perfect for driving conversions and generating leads.
  fr: Une section conçue pour encourager les utilisateurs à effectuer une action spécifique telle que s'inscrire à une newsletter, télécharger une ressource ou contacter un représentant commercial. Parfait pour augmenter les conversions et générer des prospects.

category: action
export: true

elements:
  background:
  title:
  text:
  link:
    description:
      en: A action link that directs users to a specific page or resource.
      fr: Un lien d'action qui dirige les utilisateurs vers une page ou une ressource spécifique.

properties:
  content_position:
    label: 
      en: Content Position
      fr: Position du contenu
    type: string
    default: left
    enum:
      - label: 
          en: Left
          fr: Gauche
        value: left
      - label: 
          en: Center
          fr: Centre
        value: center
      - label: 
          en: Right
          fr: Droite
        value: right
    description: 
      en: The alignment of the content within the call to action section. This is only used when the appearance is set to subtle.
      fr: L'alignement du contenu dans la section d'appel à l'action. Ceci est utilisé uniquement lorsque l'apparence est définie sur subtile.
  appearance:
    label:
      en: Appearance
      fr: Apparence
    type: string
    default: subtle
    enum:
      - label:
          en: Subtle
          fr: Subtil
        value: subtle
      - label:
          en: Fancy
          fr: Fantaisie
        value: fancy
    description:
      en: The appearance of the Call to Action.
      fr: L'apparence de l'appel à l'action.
  appearance_preset:
    label:
      en: Appearance Preset
      fr: Préréglage d'apparence
    type: string
    default: none
    enum:
      - label:
          en: None
          fr: Aucun
        value: none
      - label:
          en: Ocean
          fr: Océan
        value: ocean
      # - label:
      #     en: Rainbow
      #     fr: Arc-en-ciel
      #   value: rainbow
    description:
      en: The appearance preset of the section when appearance is set to fancy. Choose none will use the Uniweb theme applied to this section.
      fr: Le préréglage d'apparence de la section lorsque l'apparence est définie sur fantaisie. Choisir aucun utilisera le thème Uniweb appliqué à cette section.

presets:
  subtle:
    label:
      en: Subtle appearance
      fr: Apparence subtile
    properties:
      content_position: right
      appearance: subtle
      appearance_preset: none
    image: subtle.png
  fancy_ocean:
    label:
      en: Fancy appearance with ocean preset
      fr: Apparence fantaisie avec préréglage océan
    properties:
      appearance: fancy
      appearance_preset: ocean
    image: fancy_ocean.png
  # fancy_rainbow:
  #   label:
  #     en: Fancy appearance with rainbow preset
  #     fr: Apparence fantaisie avec préréglage arc-en-ciel
  #   properties:
  #     appearance: fancy
  #     appearance_preset: ocean
  #   image: fancy_ocean.png
  fancy:
    label:
      en: Fancy appearance with no preset
      fr: Apparence fantaisie sans préréglage
    properties:
      appearance: fancy
      appearance_preset: none
    image: fancy.png
