title: 
  en: Call to Action
  fr: Appel à l'action
label:
  en: Call to Action
  fr: Appel à l'action
description: 
  en: A section designed to encourage users to take a specific action such as signing up for a newsletter, downloading a resource, or contacting a sales representative. Perfect for driving conversions and generating leads.
  fr: Une section conçue pour encourager les utilisateurs à effectuer une action spécifique telle que s'inscrire à une newsletter, télécharger une ressource ou contacter un représentant commercial. Parfait pour augmenter les conversions et générer des prospects.

category: action
export: true

elements:
  background:
  link:
    description:
      en: A action link that directs users to a specific page or resource.
      fr: Un lien d'action qui dirige les utilisateurs vers une page ou une ressource spécifique.

properties:
  content_position:
    label: 
      en: Content Position
      fr: Position du contenu
    type: string
    default: left
    enum:
      - label: 
          en: Left
          fr: Gauche
        value: left
      - label: 
          en: Right
          fr: Droite
        value: right
    description: 
      en: The alignment of the content within the call to action section.
      fr: L'alignement du contenu dans la section d'appel à l'action.

presets:
  content_right:
    label:
      en: Showcase of content on the right side with a background image.
      fr: Mise en valeur du contenu sur le côté droit avec une image d'arrière-plan.
    properties:
      content_position: right
    image: content_right.png
