title: 
  en: Call to Action
  fr: Appel à l'action
label:
  en: Call to Action
  fr: Appel à l'action
description: 
  en: A section designed to encourage users to take a specific action such as signing up for a newsletter, downloading a resource, or contacting a sales representative. Perfect for driving conversions and generating leads.
  fr: Une section conçue pour encourager les utilisateurs à effectuer une action spécifique telle que s'inscrire à une newsletter, télécharger une ressource ou contacter un représentant commercial. Parfait pour augmenter les conversions et générer des prospects.

category: action
export: true

elements:
  background:
  title:
  text:
  link:
    description:
      en: A action link that directs users to a specific page or resource.
      fr: Un lien d'action qui dirige les utilisateurs vers une page ou une ressource spécifique.

properties:
  content_position:
    label: 
      en: Content Position
      fr: Position du contenu
    type: string
    default: left
    enum:
      - label: 
          en: Left
          fr: Gauche
        value: left
      - label: 
          en: Center
          fr: Centre
        value: center
      - label: 
          en: Right
          fr: Droite
        value: right
    description: 
      en: The alignment of the content within the call to action section.
      fr: L'alignement du contenu dans la section d'appel à l'action.
  appearance:
    label:
      en: Appearance
      fr: Apparence
    type: string
    default: subtle
    enum:
      - label:
          en: Subtle
          fr: Subtil
        value: subtle
      - label:
          en: Fancy
          fr: Fantaisie
        value: fancy
      - label:
          en: Motion
          fr: Mouvement
        value: motion
    description:
      en: The appearance of the Call to Action.
      fr: L'apparence de l'appel à l'action.
presets:
  subtle:
    label:
      en: Subtle appearance
      fr: Apparence subtile
    properties:
      content_position: right
      appearance: subtle
    image: subtle.png
  fancy:
    label:
      en: Fancy appearance with ocean preset
      fr: Apparence fantaisie avec préréglage océan
    properties:
      appearance: fancy
    image: fancy.png
  motion:
    label:
      en: Fancy appearance with motion preset
      fr: Apparence fantaisie avec préréglage de mouvement
    properties:
      appearance: motion
    image: motion.png
