title: 
  en: Features
  fr: Fonctionnalités
label:
  en: Features
  fr: Fonctionnalités
description: 
  en: Section showcasing a collection of features or services in a horizontal list layout. 
  fr: Section mettant en avant une collection de fonctionnalités ou de services sous forme de liste horizontale.

category: feature
export: false

elements:
  title:
  subtitle:
  link:

items:
  separator: divider
  elements:
    icon:
      description:
        en: The icon of the feature.
        fr: L'icône de la fonctionnalité.
    title:
      description:
        en: The title of the feature.
        fr: Le titre de la fonctionnalité.
    text:
      description:
        en: The description of the feature.
        fr: La description de la fonctionnalité.
    link:
      description:
        en: One or two links that put under the text content.
        fr: Un ou deux liens qui sont placés sous le contenu textuel.

properties:
  appearance:
    label:
      en: Appearance
      fr: Apparence
    type: string
    default: subtle
    enum:
      - label:
          en: Subtle
          fr: Subtil
        value: subtle
      - label:
          en: Fancy
          fr: Fantaisie
        value: fancy
    description:
      en: The appearance of the features section.
      fr: L'apparence de la section des fonctionnalités.
  appearance_preset:
    label:
      en: Appearance Preset
      fr: Préréglage d'apparence
    type: string
    default: none
    enum:
      - label:
          en: None
          fr: Aucun
        value: none
      - label:
          en: Sky
          fr: Ciel
        value: sky
    description:
      en: The appearance preset of the features when appearance is set to fancy. Choose none will use the Uniweb theme applied to this section.
      fr: Le préréglage d'apparence des fonctionnalités lorsque l'apparence est définie sur fantaisie. Choisir aucun utilisera le thème Uniweb appliqué à cette section.

images:
  - example.png