title: 
  en: Article Hub
  fr: Hub d'articles
label:
  en: Article Hub
  fr: Hub d'articles
description: 
  en: A versatile and interactive component designed to display and manage a collection of articles. Each article includes key details such as the author, title, description, publication date, and a cover image.
  fr: Un composant polyvalent et interactif conçu pour afficher et gérer une collection d'articles. Chaque article inclut des détails clés tels que l'auteur, le titre, la description, la date de publication et une image de couverture.

category: article
export: true

elements:
  title:
  subtitle:

properties:
  layout:
    label:
      en: Layout
      fr: Mise en page
    type: string
    default: grid
    enum:
      - label:
          en: Flat Grid
          fr: Grille plate
        value: grid
      - label:
          en: Grouped
          fr: Groupé
        value: grouped
    description:
      en: The layout of the articles in the hub.
      fr: La mise en page des articles dans le hub.
  
images:
  - example.png