title: 
  en: Content Teaser
  fr: Mise en avant de contenu
label:
  en: Content Teaser
  fr: Mise en avant de contenu
description: 
  en: A section that draws attention to a specific piece of content, such as a blog post, article, or product. Used to show a brief preview of the content
  fr: Une section qui attire l'attention sur un contenu spécifique, tel qu'un article de blog, un article ou un produit. Utilisé pour afficher un bref aperçu du contenu

category: content
export: true

elements:
  title:
  subtitle:
  link:
    description:
      en: A link put on the right side of the content teaser. It can direct users to a specific page or resource.
      fr: Un lien placé sur le côté droit de la mise en avant de contenu. Il peut diriger les utilisateurs vers une page ou une ressource spécifique.

items:
  separator: divider
  elements:
    background:
    pretitle:
    title:
    text:
    link:
      type: link
      description: 
        en: A link make the item clickable.
        fr: Un lien rend l'élément cliquable.

properties:
  card_size:
    label:
      en: Card Size
      fr: Taille de la carte
    type: string
    default: md
    enum:
      # - label:
      #     en: Small
      #     fr: Petit
      #   value: small
      - label:
          en: Medium
          fr: Moyen
        value: md
      - label:
          en: Large
          fr: Grand
        value: lg
    description:
      en: The size of the content teaser card.
      fr: La taille de la carte de mise en avant de contenu.

images:
  - example.png