title: 
  en: Footer
  fr: Pied de page
label:
  en: Footer
  fr: Pied de page
description:
  en: A footer component renders the navigation to the next and previous pages.
  fr: Un composant de pied de page rend la navigation vers les pages suivantes et précédentes.

export: true

images:
  - example.png