title: 
  en: Right Panel
  fr: Panneau de droite
label:
  en: Right Panel
  fr: Panneau de droite
description:
  en: A component that renders a list of links to the topics of the current page.
  fr: Un composant qui rend une liste de liens vers les sujets de la page actuelle.

export: true
  
images:
  - example.png