title:
  en: Reference Viewer
  fr: Visualiseur de référence
label:
  en: Reference - Item
  fr: Référence
description:
  en: Showing the detail of a reference profile.
  fr: Affichage du détail d'un profil de référence.
input:
  type: reference
  limit: false
  
category: reference
export: true

elements:
    title:

images:
  - example.png
