import React from 'react';
// import { CurrencyCode as currency_code } from 'uniweb-core';
import getFieldValue from '../utils/fieldValueParser';

export const currency_code = {
    'afghan afghani': 'AFN',
    'afghani afgan': 'AFN',
    'albanian lek': 'ALL',
    'lek albanais': 'ALL',
    'algerian dinar': 'DZD',
    'dinar algérien': 'DZD',
    'angolan kwanza': 'AOA',
    'kwanza angolais': 'AOA',
    'argentine peso': 'ARS',
    'peso argentin': 'ARS',
    'armenian dram': 'AMD',
    'dram arménien': 'AMD',
    'aruban florin': 'AWG',
    'florin arubais': 'AWG',
    'australian dollar': 'AUD',
    'dollar australien': 'AUD',
    'azerbaijani manat': 'AZN',
    'manat azerbaidjanais': 'AZN',
    'bahamian dollar': 'BSD',
    'dollar bahamien': 'BSD',
    'bahraini dinar': 'BHD',
    'dinar bahrëini': 'BHD',
    'bangladeshi taka': 'BDT',
    'taka bangladeshi': 'BDT',
    'barbados dollar': 'BBD',
    'dollar barbadien': 'BBD',
    'belarusian ruble': 'BYN',
    'rouble biélorusse': 'BYN',
    'belize dollar': 'BZD',
    'dollar bélizien': 'BZD',
    'bermudian dollar': 'BMD',
    'dollar bermudien': 'BMD',
    'bhutanese ngultrum': 'BTN',
    'ngultrum bhoutanais': 'BTN',
    boliviano: 'BOB',
    'boliviano bolivien': 'BOB',
    'bosnia and herzegovina convertible mark': 'BAM',
    'marka bosniaque': 'BAM',
    'botswana pula': 'BWP',
    'pula botswanéen': 'BWP',
    'brazilian real': 'BRL',
    'real brésilien': 'BRL',
    'brunei dollar': 'BND',
    'dollar brunéin': 'BND',
    'bulgarian lev': 'BGN',
    'lev bulgare': 'BGN',
    'burundian franc': 'BIF',
    'franc burundais': 'BIF',
    'cambodian riel': 'KHR',
    'rien cambodgien': 'KHR',
    'canadian dollar': 'CAD',
    'dollar canadien': 'CAD',
    'cape verde escudo': 'CVE',
    'escudo capverdien': 'CVE',
    'cayman islands dollar': 'KYD',
    'dollar des îles caïmans': 'KYD',
    'chilean peso': 'CLP',
    'peso chilien': 'CLP',
    'chinese yuan': 'CNY',
    'yuan chinois': 'CNY',
    'colombian peso': 'COP',
    'peso colombien': 'COP',
    'comoro franc': 'KMF',
    'franc comorien': 'KMF',
    'congolese franc': 'CDF',
    'franc congolais': 'CDF',
    'cordoba oro': 'NIO',
    'oro de cordoba': 'NIO',
    'costa rican colon': 'CRC',
    'colon costaricain': 'CRC',
    'croatian kuna': 'HRK',
    'kuna croate': 'HRK',
    'cuban peso': 'CUP',
    'peso cubain': 'CUP',
    'czech koruna': 'CZK',
    'couronne tchèque': 'CZK',
    'danish krone': 'DKK',
    'couronne danoise': 'DKK',
    'djiboutian franc': 'DJF',
    'franc djiboutien': 'DJF',
    'dominican peso': 'DOP',
    'peso dominicain': 'DOP',
    'east caribbean dollar': 'XCD',
    'dollar des caraïbes': 'XCD',
    'egyptian pound': 'EGP',
    'livre égyptienne': 'EGP',
    'eritrean nakfa': 'ERN',
    'nafka erythréen': 'ERN',
    'ethiopian birr': 'ETB',
    'birr éthiopien': 'ETB',
    euro: 'EUR',
    'falkland islands pound': 'FKP',
    'livre des îles malouines': 'FKP',
    'fiji dollar': 'FJD',
    'dollar fidjien': 'FJD',
    'gambian dalasi': 'GMD',
    'dalasi gambien': 'GMD',
    'georgian lari': 'GEL',
    'lari georgien': 'GEL',
    'ghanaian cedi': 'GHS',
    'cedi ghanéen': 'GHS',
    'gibraltar pound': 'GIP',
    'livre de gibraltar': 'GIP',
    'guatemalan quetzal': 'GTQ',
    'quetzal guatémaltèque': 'GTQ',
    'guinean franc': 'GNF',
    'franc guinéen': 'GNF',
    'guyanese dollar': 'GYD',
    'dollar guyannais': 'GYD',
    'haitian gourde': 'HTG',
    'gourde haïtien': 'HTG',
    'honduran lempira': 'HNL',
    'lempira hondurien': 'HNL',
    'hong kong dollar': 'HKD',
    'dollar hongkongais': 'HKD',
    'hungarian forint': 'HUF',
    'forint hongrois': 'HUF',
    'icelandic króna': 'ISK',
    'couronne islandaise': 'ISK',
    'indian rupee': 'INR',
    'roupie indienne': 'INR',
    'indonesian rupiah': 'IDR',
    'roupie indonésienne': 'IDR',
    'iranian rial': 'IRR',
    'rial iranien': 'IRR',
    'iraqi dinar': 'IQD',
    'dinar irakien': 'IQD',
    'israeli new sheqel': 'ILS',
    'nouveau shekel israélien': 'ILS',
    'jamaican dollar': 'JMD',
    'dollar jamaicain': 'JMD',
    'japanese yen': 'JPY',
    'yen japonais': 'JPY',
    'jordanian dinar': 'JOD',
    'dinar jordanien': 'JOD',
    'kazakhstani tenge': 'KZT',
    'tenge kazakh': 'KZT',
    'kenyan shilling': 'KES',
    'shilling kenian': 'KES',
    'kuwaiti dinar': 'KWD',
    'dinar koweitien': 'KWD',
    'kyrgyzstani som': 'KGS',
    'som kirghiz': 'KGS',
    'lao kip': 'LAK',
    'kip laotien': 'LAK',
    'latvian lats': 'LVL',
    'lats letton': 'LVL',
    'lebanese pound': 'LBP',
    'livre libanaise': 'LBP',
    'lesotho loti': 'LSL',
    'loti lésothan': 'LSL',
    'liberian dollar': 'LRD',
    'dollar libérien': 'LRD',
    'libyan dinar': 'LYD',
    'dinar libyen': 'LYD',
    lilangeni: 'LTL',
    'lithuanian litas': 'LTL',
    'litas lituanien': 'LTL',
    'macanese pataca': 'MOP',
    'pataca de macao': 'MOP',
    'macedonian denar': 'MKD',
    'denar macédonien': 'MKD',
    'malagasy ariary': 'MGA',
    'ariary malgache': 'MGA',
    'malawian kwacha': 'MWK',
    'kwacha malawite': 'MWK',
    'malaysian ringgit': 'MYR',
    'ringgit malaisien': 'MYR',
    'maldivian rufiyaa': 'MVR',
    'rufiyaa maldivien': 'MVR',
    'mauritanian ouguiya': 'MRO',
    'ouguiya mauritanien': 'MRO',
    'mauritian rupee': 'MUR',
    'roupie mauricienne': 'MUR',
    'mexican peso': 'MXN',
    'peso mexicain': 'MXN',
    'moldovan leu': 'MDL',
    'leu moldave': 'MDL',
    'mongolian tugrik': 'MNT',
    'tugrik mongolien': 'MNT',
    'moroccan dirham': 'MAD',
    'dirham marocain': 'MAD',
    'mozambican metical': 'MZN',
    'metical mozambicain': 'MZN',
    'myanma kyat': 'BUK',
    'kyat birman': 'BUK',
    'namibian dollar': 'NAD',
    'dollar namibien': 'NAD',
    'nepalese rupee': 'NPR',
    'roupie népalaise': 'NPR',
    'netherlands antillean guilder': 'ANG',
    'florin des antilles néerlandaises': 'ANG',
    'new taiwan dollar': 'TWD',
    'nouveau dollar de taïwan': 'TWD',
    'new zealand dollar': 'NZD',
    'dollar néo-zélandais': 'NZD',
    'nigerian naira': 'NGN',
    'naira nigérien': 'NGN',
    'north korean won': 'KPW',
    'won nord-coréen': 'KPW',
    'norwegian krone': 'NOK',
    'couronne norvégienne': 'NOK',
    'omani rial': 'OMR',
    'rial omanais': 'OMR',
    'pakistani rupee': 'PKR',
    'roupie pakistanaise': 'PKR',
    'panamanian balboa': 'PAB',
    'balboa panaméen': 'PAB',
    'papua new guinean kina': 'PGK',
    'kina papouan': 'PGK',
    'paraguayan guaraní': 'PYG',
    'guarani paraguayen': 'PYG',
    'peruvian nuevo sol': 'PEN',
    'nuevo sol péruvien': 'PEN',
    'philippine peso': 'PHP',
    'peso philippin': 'PHP',
    'polish z?oty': 'PLN',
    'zloty polonais': 'PLN',
    'pound sterling': 'GBP',
    'livre sterling': 'GBP',
    'qatari rial': 'QAR',
    'rial quatarien': 'QAR',
    'romanian new leu': 'RON',
    'leu roumain': 'RON',
    'russian rouble': 'RUB',
    'rouble russe': 'RUB',
    'rwandan franc': 'RWF',
    'franc rwandais': 'RWF',
    'saint helena pound': 'SHP',
    'livre de saint-hélène': 'SHP',
    'samoan tala': 'WST',
    'tala samoan': 'WST',
    'são tomé and príncipe dobra': 'STD',
    'dobra santoméen': 'STD',
    'saudi riyal': 'SAR',
    'riyal saoudien': 'SAR',
    'serbian dinar': 'RSD',
    'dinar serbe': 'RSD',
    'seychelles rupee': 'SCR',
    'roupie seychelloise': 'SCR',
    'sierra leonean leone': 'SLL',
    'leone sierra-léonais': 'SLL',
    'singapore dollar': 'SGD',
    'dollar singapourien': 'SGD',
    'solomon islands dollar': 'SBD',
    'dollar des îles solomon': 'SBD',
    'somali shilling': 'SOS',
    'shilling somalien': 'SOS',
    'south african rand': 'ZAR',
    'rand sud-africain': 'ZAR',
    'south korean won': 'KRW',
    'won sud-coréen': 'KRW',
    'sri lanka rupee': 'LKR',
    'roupie srilankaise': 'LKR',
    'sudanese pound': 'SDG',
    'livre sudanaise': 'SDG',
    'surinamese dollar': 'SRD',
    'dollar surinamien': 'SRD',
    'swedish krona/kronor': 'SEK',
    'couronne suédoise': 'SEK',
    'swiss franc': 'CHF',
    'franc suisse': 'CHF',
    'syrian pound': 'SYP',
    'livre syrienne': 'SYP',
    'tajikistani somoni': 'TJS',
    'somoni tadjik': 'TJS',
    'tanzanian shilling': 'TZS',
    'shilling tanzanien': 'TZS',
    'thai baht': 'THB',
    'baht thailandais': 'THB',
    "tongan pa'anga": 'TOP',
    "pa'anga tonguien": 'TOP',
    'trinidad and tobago dollar': 'TTD',
    'dollar trinidadien': 'TTD',
    'tunisian dinar': 'TND',
    'dinar tunisien': 'TND',
    'turkish lira': 'TRY',
    'livre turque': 'TRY',
    'turkmenistani manat': 'TMT',
    'manat turkmène': 'TMM',
    'ugandan shilling': 'UGX',
    'shilling ougandais': 'UGX',
    'ukrainian hryvnia': 'UAH',
    'hryvnia ukrainienne': 'UAH',
    'united arab emirates dirham': 'AED',
    'dirham des émirats arabes unis': 'AED',
    'united states dollar': 'USD',
    'dollar américain': 'USD',
    'uruguayan peso': 'UYU',
    'peso uruguayen': 'UYU',
    'uzbekistan som': 'UZS',
    'soum ouzbek': 'UZS',
    'vanuatu vatu': 'VUV',
    'vatu vanuatuan': 'VUV',
    'venezuelan bolivar fuerte': 'VEF',
    'bolivar fuerte vénézuélien': 'VEF',
    'vietnamese dong': 'VND',
    'dong vietnamien': 'VND',
    'yemeni rial': 'YER',
    'rial yéméni': 'YER',
    'zambian kwacha': 'ZMW',
    'kwacha zambien': 'ZMW',
    'zimbabwe dollar': 'ZWD',
    'dollar zimbabwéen': 'ZWD',
};

export default function CurrencyResolver(props) {
    const { amount = {}, currency = {}, convertedAmount, editMode } = props;

    // const currencyFieldValue = JSON.parse(currency).value;
    const currencyFieldValue = currency.value;

    let currencyConfig = {};

    if (currencyFieldValue) {
        const currencyCode = currency_code[currencyFieldValue.toLowerCase()];
        if (currencyCode) {
            currencyConfig = { style: 'currency', currency: currencyCode };
        }
    }

    // const amountFieldName = JSON.parse(amount).name;
    const amountFieldName = amount.name;

    const amountValue = getFieldValue(amount, {
        label: [amountFieldName],
        editMode,
        numberFormat: currencyConfig,
        strong: [`${amountFieldName}:label`],
    });
    const currencyValue = getFieldValue(currency, { editMode });
    const convertedAmountValue = getFieldValue(convertedAmount, {
        editMode,
        numberFormat: { style: 'currency', currency: 'CAD' },
    });

    if (amountValue || currencyValue || (convertedAmountValue && convertedAmountValue != 0))
        return (
            <span>
                <span>{amountValue} </span>
                <span className={`italic text-gray-700`}>{currencyValue} </span>
                {convertedAmountValue && convertedAmountValue != 0 ? (
                    <span className={`text-gray-500`}>({convertedAmountValue})</span>
                ) : (
                    ''
                )}
            </span>
        );

    return null;
}
