title: 
  en: Code Hero
  fr: Mise en avant de contenu
label:
  en: Code Hero
  fr: Mise en avant de contenu
description:
  en: A prominent section designed to grab attention, featuring a bold title and visually engaging code snippets. Perfect for highlighting key messages or showcasing impactful content at the top of a page.
  fr: Une section importante conçue pour attirer l'attention, avec un titre audacieux et des extraits de code visuellement attrayants. Parfait pour mettre en avant des messages clés ou présenter un contenu percutant en haut d'une page.

category: hero
export: true


elements:
  title:
  subtitle:
  link:
    description:
      en: One or two action links that direct users to a specific page or resource.
      fr: Un ou deux liens d'action qui dirigent les utilisateurs vers une page ou une ressource spécifique.
  code:
    label:
      en: JSON properties
      fr: Propriétés JSON
    description:
      en: The properties of the code snippets such as title and description.
      fr: Les propriétés des extraits de code tels que le titre et la description.

items:
  separator: section
  limit: 1
  elements:
    code:
      label:
        en: Code Snippet
        fr: Extrait de code
      description:
        en: The Code Snippet to be displayed in the Code Hero.
        fr: L'extrait de code à afficher dans la Mise en avant de contenu.

images:
  - example.png