title: 
  en: Video Carousel
  fr: Carrousel de Videos
label:  
  en: Video Carousel
  fr: Carrousel de Videos
description:
  en: A video carousel component that can be used to showcase videos. Only local uploaded videos are supported.
  fr: Un composant de carrousel de vidéos qui peut être utilisé pour mettre en valeur des vidéos. Seules les vidéos téléchargées localement sont prises en charge.

category: media
export: true

elements:
  title:
  media:
    type: video
    description: 
      en: The showcase videos.
      fr: Les vidéos de présentation.
      
images:
  - example.png