title:
  en: Product Catalog
  fr: Catalogue de produits
label:
  en: Product Catalog
  fr: Catalogue de produits
description:
  en: A versatile component that displays a collection of products with search, filter, and sort functionality. Each product includes a detailed description and image for an engaging browsing experience.
  fr: Un composant polyvalent qui affiche une collection de produits avec des fonctionnalités de recherche, de filtrage et de tri. Chaque produit comprend une description détaillée et une image pour une expérience de navigation captivante.

category: content
export: true