title:
    en: References List
    fr: Liste de références
label:
    en: References - List
    fr: Références - Liste
description:
    en: Showing the references from the input in a list with filtering and sorting.
    fr: Affichage des références de l'entrée dans une liste avec filtrage et tri.
input:
    type: reference
    limit: false

category: reference
export: true

elements:
    title:

properties:
    groupReferences:
        label:
            en: Group references
            fr: Grouper les références
        type: boolean
        default: false
        description:
            en: Group references by the reference type.
            fr: Grouper les références par type de référence.

images:
    - example.png
