title: 
  en: Logo Carousel
  fr: Carrousel de logos
label:  
  en: Logo Carousel
  fr: Carrousel de logos
description:
  en: A logo carousel component that can be used to showcase logos.
  fr: Un composant de carrousel de logos qui peut être utilisé pour mettre en valeur des logos.

export: true

elements:
  title:
  media:
    type: image
    description: 
      en: The showcase images.
      fr: Les images de présentation.

properties:
  speed:
    label:
      en: Speed
      fr: Vitesse
    type: string
    default: normal
    enum:
      - label:
          en: Slow
          fr: Lent
        value: slow
      - label:
          en: Normal
          fr: Normal
        value: normal
      - label:
          en: Fast
          fr: Rapide
        value: fast
    description:
      en: The speed of the carousel animation.
      fr: La vitesse de l'animation du carrousel.

images:
  - example.png