title: 
  en: Icon Grid
  fr: Grille d'icônes
label:
  en: Icon Grid
  fr: Grille d'icônes
description: 
  en: A section to show a selection of icons, logos, or other images.
  fr: Section permettant d'afficher une sélection d'icônes, de logos ou d'autres images.

category: content
export: true

assets:
  Screenshot.png:
    title: 
      en: Basic usage.
      fr: Utilisation de base.

elements:
  title:

items:
  separator: divider
  elements:
    background:

images:
  - example.png
