title:
    en: Embed Content
    fr: Intégrer du contenu
label:
    en: Content - iFrame
    fr: Contenu - iFrame
description:
    en: Allows you to display content from another website directly on your own page.
    fr: Vous permet d'afficher le contenu d'un autre site Web directement sur votre propre page.

category: content
export: true

elements:
    title:
    link:
        description:
            en: The URL of the website you want to embed.
            fr: L'URL du site Web que vous souhaitez intégrer.

properties:
    vertical_padding:
        label:
            en: Vertical Spacing
            fr: Espacement vertical
        type: string
        default: lg
        enum:
            - label:
                  en: Large
                  fr: Large
              value: lg
            - label:
                  en: Medium
                  fr: Moyen
              value: md
            - label:
                  en: Small
                  fr: Petit
              value: sm
            - label:
                  en: None
                  fr: Aucun
              value: none
        description:
            en: The space on top and bottom of the layout.
            fr: L'espace en haut et en bas de la mise en page.
    iframe_height:
        label:
            en: iFrame Height (see description)
            fr: Hauteur de l'iFrame (voir description)
        type: string
        default: 56.25%
        description:
            en: Controls the vertical space of the embedded content. You can set a fixed height using values like 800px, a responsive aspect ratio using a percentage like 56.25% (for 16:9), or use viewport height such as 100vh to make it fill the screen. If left blank, it defaults to 56.25%. Minimum height is 200px.
            fr: Contrôle l'espace vertical du contenu intégré. Vous pouvez définir une hauteur fixe en utilisant des valeurs comme 800px, un rapport d'aspect réactif en utilisant un pourcentage comme 56,25 % (pour 16:9), ou utiliser la hauteur de la fenêtre d'affichage telle que 100vh pour le faire remplir l'écran. Si laissé vide, il par défaut à 56,25 %. La hauteur minimale est de 200px.

images:
    - example.png
