title:
    en: Embed Content
    fr: Intégrer du contenu
label:
    en: Content - iFrame
    fr: Contenu - iFrame
description:
    en: Allows you to display content from another website directly on your own page.
    fr: Vous permet d'afficher le contenu d'un autre site Web directement sur votre propre page.

category: content
export: true

elements:
    title:
    link:
        description:
            en: The URL of the website you want to embed.
            fr: L'URL du site Web que vous souhaitez intégrer.

properties:
    vertical_padding:
        label:
            en: Vertical Spacing
            fr: Espacement vertical
        type: string
        default: lg
        enum:
            - label:
                  en: Large
                  fr: Large
              value: lg
            - label:
                  en: Medium
                  fr: Moyen
              value: md
            - label:
                  en: Small
                  fr: Petit
              value: sm
            - label:
                  en: None
                  fr: Aucun
              value: none
        description:
            en: The space on top and bottom of the layout.
            fr: L'espace en haut et en bas de la mise en page.

images:
    - example.png
