title: 
  en: Media Footer
  fr: Pied de page média
label:
  en: Footer - Media
  fr: Pied de page - Média
description: 
  en: Use this footer when you want to include more content and branding. It supports a logo, grouped navigation links, media/social links, copyright text, a newsletter form, and an optional back-to-top button.  
  fr: Utilisez ce pied de page lorsque vous souhaitez inclure plus de contenu et de marque. Il prend en charge un logo, des liens de navigation regroupés, des liens médias/sociaux, du texte de droits d'auteur, un formulaire d'abonnement à la newsletter et un bouton facultatif de retour en haut de page.

category: footer
export: true

elements:
  title:
    description: 
      en: The text put beside the logo.
      fr: Le texte mis à côté du logo.
  subtitle:
    description: 
      en: The text put under the logo.
      fr: Le texte mis sous le logo.
  text:
    description: 
      en: The text to display at the bottom of the footer, usually used for copyright information.
      fr: Le texte à afficher en bas du pied de page, généralement utilisé pour les informations de droits d'auteur.
  icon:
    type: icon
    description: 
      en: The logo displayed in the footer, typically representing your site or department.
      fr: Le logo affiché dans le pied de page, représentant généralement votre site ou votre département.
  list:
    type: bullet
    title: 
      en: Navigation Links
      fr: Liens de navigation
    description:
      en: Display grouped external links in the footer to help users access related resources. To create groups, enter a top-level item as the group title (e.g., “Resources”), then nest external link items under it (e.g., “Blog”, “Videos”, “Media Hub”). To add multiple groups, continue in the same list without leaving empty lines. After finishing a group's links, go back to the top level and enter a new group title followed by its nested links.
      fr: Affichez des liens externes regroupés dans le pied de page pour aider les utilisateurs à accéder aux ressources connexes. Pour créer des groupes, entrez un élément de niveau supérieur comme titre de groupe (par exemple, "Ressources"), puis imbriquez les éléments de lien externe en dessous (par exemple, "Blog", "Vidéos", "Centre multimédia"). Pour ajouter plusieurs groupes, continuez dans la même liste sans laisser de lignes vides. Après avoir terminé les liens d'un groupe, revenez au niveau supérieur et entrez un nouveau titre de groupe suivi de ses liens imbriqués.
  link:
    type: link
    description: 
        en: One or more external links, usually to social media. These will appear in the branding area, below the logo, title, and subtitle. Media links will be displayed as icons.
        fr: Un ou plusieurs liens externes, généralement vers les réseaux sociaux. Ceux-ci apparaîtront dans la zone de marque, sous le logo, le titre et le sous-titre. Les liens médias seront affichés sous forme d'icônes.

properties:
  with_newsletter:
    type: boolean
    label: 
      en: Newsletter Subscription
      fr: Abonnement à la newsletter
    default: true
    description: 
      en: Whether or not to display the newsletter subscription form on the right side of the footer.
      fr: Afficher ou non le formulaire d'abonnement à la newsletter sur le côté droit du pied de page.
  with_back_to_top:
    type: boolean
    label: 
      en: Back to Top Button
      fr: Bouton Retour en haut
    default: false
    description: 
      en: Whether or not to display the back to top button on the right side of the footer.
      fr: Afficher ou non le bouton de retour en haut sur le côté droit du pied de page.

presets:
  newsletter_back_to_top:
    label:
      en: Newsletter & Back to Top
      fr: Newsletter et Retour en haut
    with_newsletter: true
    with_back_to_top: true
    image: newsletter_back_to_top.png