title: 
  en: Feature
  fr: Fonctionnalité
label:
  en: Feature
  fr: Fonctionnalité
description: 
  en: Displays section content in different styles, showing title, description and links. Best used to showcase product features or services. Can receive subsections to display sub-feature content.
  fr: Affiche le contenu de la section dans différents styles, montrant le titre, la description et les liens. Idéal pour mettre en valeur les fonctionnalités des produits ou services. Peut recevoir des sous-sections pour afficher le contenu des sous-fonctionnalités.

category: feature
export: true

elements:
  title:
  subtitle:
  link:

items:
  separator: section
  category: Feature Item

properties:
  appearance:
    label:
      en: Appearance Style
      fr: Style d'apparence
    type: string
    default: standard
    enum:
      - label:
          en: Standard
          fr: Standard
        value: standard
      - label:
          en: Loose
          fr: Lâche
        value: loose
      - label:
          en: Iconic
          fr: Iconique
        value: iconic
    description:
      en: The appearance of the features section.
      fr: L'apparence de la section des fonctionnalités.
  sub_content_layout:
    label:
      en: Sub-content Style
      fr: Style du sous-contenu
    type: string
    default: grid_sm
    enum:
      - label:
          en: Grid with small size content
          fr: Grille avec contenu de petite taille
        value: grid_sm
      - label:
          en: Grid with large size content
          fr: Grille avec contenu de grande taille
        value: grid_lg
      - label:
          en: Grid with medium size content
          fr: Grille avec contenu de taille moyenne
        value: grid_md
      - label:
          en: Full width content
          fr: Contenu pleine largeur
        value: full
    description:
      en: The layout of the sub-content.
      fr: La mise en page du sous-contenu.

presets:
  standard:
    label:
      en: Standard Feature with Catching Card style sub-features
      fr: Fonctionnalité standard avec des sous-fonctionnalités de style Carte attrayante
    properties:
      appearance: standard
    image: standard.png
  loose:
    label:
      en: Loose Feature with rich sub-features
      fr: Fonctionnalité lâche avec des sous-fonctionnalités riches
    properties:
      appearance: loose
    image: loose.png
  iconic:
    label:
      en: Iconic Feature with basic sub-features
      fr: Fonctionnalité iconique avec des sous-fonctionnalités basiques
    properties:
      appearance: iconic
    image: iconic.png
  standard_full:
    label:
      en: Standard Feature with Full-width sub-features
      fr: Fonctionnalité standard avec des sous-fonctionnalités pleine largeur
    properties:
      appearance: standard
      sub_content_layout: full
    image: standard_full.png