title: 
  en: Feature
  fr: Fonctionnalité
label:
  en: Feature
  fr: Fonctionnalité
description: 
  en: Displays section content in different styles, showing title, description and two links. Best used to showcase product features or services. Can receive subsections to display sub-feature content.
  fr: Affiche le contenu de la section dans différents styles, montrant le titre, la description et deux liens. Idéal pour mettre en avant les fonctionnalités du produit ou les services. Peut recevoir des sous-sections pour afficher le contenu des sous-fonctionnalités.

category: feature
export: true

elements:
  title:
  subtitle:
  link:
    description:
      en: One or two links that put under the text content.
      fr: Un ou deux liens qui sont placés sous le contenu textuel.

properties:
  appearance:
    label:
      en: Appearance
      fr: Apparence
    type: string
    default: standard
    enum:
      - label:
          en: Standard
          fr: Standard
        value: standard
      - label:
          en: Loose
          fr: Lâche
        value: loose
      - label:
          en: Iconic
          fr: Iconique
        value: iconic
    description:
      en: The appearance of the features section.
      fr: L'apparence de la section des fonctionnalités.
 
presets:
  standard:
    label:
      en: Standard Feature with Catching Card style sub-features
      fr: Fonctionnalité standard avec des sous-fonctionnalités de style Carte attrayante
    properties:
      appearance: standard
    image: standard.png
  loose:
    label:
      en: Loose Feature with rich sub-features
      fr: Fonctionnalité lâche avec des sous-fonctionnalités riches
    properties:
      appearance: loose
    image: loose.png