title: 
  en: Details
  fr: Détails
label:
  en: Details - Accordion
  fr: Détails - Accordéon
description: 
  en: Explain things or answer questions using collapsable blocks of text. Commonly known as an "accordion" section. Content alignment is controlled by the title alignment in the editor.
  fr: Expliquez des choses ou répondez à des questions en utilisant des blocs de texte réductibles. Communément appelé une section "accordéon". L'alignement du contenu est contrôlé par l'alignement du titre dans l'éditeur.

category: content
export: true

elements:
  title:
  subtitle:

items:
  separator: divider
  elements:
    title:
    text:

presets:
  right:
    label:
      en: Content on the Right
      fr: Contenu à droite
    properties:
      alignment: right
    image: right.png
  center:
    label:
      en: Content in the Center
      fr: Contenu au centre
    properties:
      alignment: center
    image: center.png
  left:
    label:
      en: Content on the Left
      fr: Contenu à gauche
    properties:
      alignment: left
    image: left.png