title: 
  en: FAQ
  fr: FAQ
label:
  en: FAQ
  fr: FAQ
description: 
  en: The FAQ section displays a list of frequently asked questions with their answers.
  fr: La section FAQ affiche une liste de questions fréquemment posées avec leurs réponses.

category: content
export: true
