title: 
  en: FAQ
  fr: FAQ
label:
  en: FAQ
  fr: FAQ
description: 
  en: The FAQ section displays a list of frequently asked questions with their answers.
  fr: La section FAQ affiche une liste de questions fréquemment posées avec leurs réponses.

category: content
export: true

elements:
  title:
  subtitle:

items:
  separator: divider
  elements:
    title:
      description:
        en: The title of the FAQ section.
        fr: Le titre de la section FAQ.
    text:
      description:
        en: The answer to the question.
        fr: La réponse à la question.
   
images:
  - example.png