title: 
  en: Features
  fr: Fonctionnalités
label:
  en: Features
  fr: Fonctionnalités
description: 
  en: Section showcasing a collection of features or services in a horizontal list layout. 
  fr: Section mettant en avant une collection de fonctionnalités ou de services sous forme de liste horizontale.

category: feature
export: true