title:
    en: Website Template
    fr: Modèle de site Web
label:
    en: Website Template
    fr: Modèle de site Web
description:
    en: A component showcasing a website template with description in details and live preview side by side.
    fr: Un composant présentant un modèle de site Web avec une description détaillée et un aperçu en direct côte à côte.

category: template
export: true
