title: 
  en: Timeline
  fr: Chronologie
label:
  en: Timeline
  fr: Chronologie
description: 
  en: A section to show a visual timeline and progression throughout multiple steps.
  fr: Une section pour montrer une chronologie visuelle et une progression à travers plusieurs étapes.

category: content
export: true

elements:
  background:
  pretitle:
  title:
  subtitle:

items:
  separator: divider
  elements:
    title:
    text:

images:
  example:
    label:
      en: Example of showing a timeline with 3 steps.
      fr: Exemple d'affichage d'une chronologie avec 3 étapes.
    image: example.png
