title:
  en: Content Wrapper
  fr: Enveloppe de contenu
label:
  en: Content Wrapper
  fr: Enveloppe de contenu
description:
  en: A section that wraps content (sub-components) with a title, subtitle and a optional endnote.
  fr: Une section qui enveloppe le contenu (sous-composants) avec un titre, un sous-titre et une note de fin facultative.

category: content
export: true

elements:
  title:
  subtitle:
  text:
    description:
      en: The optional endnote text put under the sub-components content.
      fr: Le texte de la note de fin facultative placé sous le contenu des sous-composants.

images:
  - example.png