title:
  en: Content Wrapper
  fr: Enveloppe de contenu
label:
  en: Content Wrapper
  fr: Enveloppe de contenu
description:
  en: A section that wraps content (sub-components) with a title, subtitle and a optional endnote.
  fr: Une section qui enveloppe le contenu (sous-composants) avec un titre, un sous-titre et une note de fin facultative.

category: content
export: true

elements:
  title:
  subtitle:
  text:
    description:
      en: The optional endnote text put under the sub-components content.
      fr: Le texte de la note de fin facultative placé sous le contenu des sous-composants.

items:
  separator: section
  category: Any section type

properties:
  padding_vertical:
    label:
      en: Vertical Padding
      fr: Rembourrage vertical
    type: string
    default: regular
    enum:
      - label:
          en: None
          fr: Aucun
        value: none
      - label:
          en: Small
          fr: Petit
        value: small
      - label:
          en: Regular
          fr: Régulier
        value: regular
    description:
      en: The vertical padding of the content wrapper.
      fr: Le rembourrage vertical de l'enveloppe de contenu.
  
images:
  - example.png