title:
    en: Basic Cards
    fr: Cartes de base
label:
    en: Cards - Basic
    fr: Cartes - De base
description:
    en: A component to show distinct pieces of information each with their own visual card.
    fr: Un composant permettant de présenter des éléments d'information distincts, chacun avec sa propre carte visuelle.

category: cards
export: true

elements:
    title:
    subtitle:

properties:
    size:
        label:
            en: Card Size
            fr: Taille de la carte
        type: string
        default: small
        enum:
            - label:
                  en: Small
                  fr: Petit
              value: small
            - label:
                  en: Medium
                  fr: Moyen
              value: regular
            - label:
                  en: Large
                  fr: Grand
              value: large
            - label:
                  en: Extra Large
                  fr: Très grand
              value: xlarge
    layout:
        label:
            en: Cards Layout
            fr: Disposition des cartes
        type: string
        default: start
        enum:
            - label:
                  en: Left-aligned
                  fr: Aligné à gauche
              value: start
            - label:
                  en: Right-aligned
                  fr: Aligné à droite
              value: end
            - label:
                  en: Centered
                  fr: Centré
              value: center
            - label:
                  en: Evenly spaced
                  fr: Espacement égal
              value: space-around
    vertical_padding:
        label:
            en: Vertical Spacing
            fr: Espacement vertical
        type: string
        default: lg
        enum:
            - label:
                  en: Large
                  fr: Large
              value: lg
            - label:
                  en: Medium
                  fr: Moyen
              value: md
            - label:
                  en: Small
                  fr: Petit
              value: sm
            - label:
                  en: None
                  fr: Aucun
              value: none
        description:
            en: The space on top and bottom of the layout.
            fr: L'espace en haut et en bas de la mise en page.
    image_aspect_ratio:
        label:
            en: Image Aspect Ratio
            fr: Ratio d'aspect de l'image
        type: string
        default: landscape
        enum:
            - label:
                  en: Landscape
                  fr: Paysage
              value: landscape
            - label:
                  en: Portrait
                  fr: Portrait
              value: portrait
            - label:
                  en: Square
                  fr: Carré
              value: square
        description:
            en: The aspect ratio of the image.
            fr: Le ratio d'aspect de l'image.

items:
    separator: divider
    elements:
        background:
        title:
        subtitle:
        text:
        link:

images:
    - example.png
