title: 
  en: Page Footer
  fr: Pied de page
label:
  en: Footer
  fr: Pied de page
description: 
  en: Use this footer when you want a simple and automatic layout. It can mirror your site's navigation structure and optionally show a language toggle.
  fr: Utilisez ce pied de page lorsque vous souhaitez une mise en page simple et automatique. Il peut refléter la structure de navigation de votre site et afficher en option un basculement de langue.

category: footer
export: true

elements:
  title:
    description: 
      en: The copyright text.
      fr: Le texte des droits d'auteur.
  list:
    type: list
    title: 
      en: Navigation Links
      fr: Liens de navigation
    description:
      en: Display grouped external links in the footer to help users access related resources. To create groups, enter a top-level item as the group title (e.g., “Resources”), then nest external link items under it (e.g., “Blog”, “Videos”, “Media Hub”). To add multiple groups, continue in the same list without leaving empty lines. After finishing a group's links, go back to the top level and enter a new group title followed by its nested links.
      fr: Affichez des liens externes regroupés dans le pied de page pour aider les utilisateurs à accéder aux ressources connexes. Pour créer des groupes, entrez un élément de niveau supérieur comme titre de groupe (par exemple, "Ressources"), puis imbriquez les éléments de lien externe en dessous (par exemple, "Blog", "Vidéos", "Centre multimédia"). Pour ajouter plusieurs groupes, continuez dans la même liste sans laisser de lignes vides. Après avoir terminé les liens d'un groupe, revenez au niveau supérieur et entrez un nouveau titre de groupe suivi de ses liens imbriqués.

properties:
  mode:
    type: string
    label: 
      en: Navigation Links Generation Mode
      fr: Mode de génération des liens de navigation
    enum:
      - label:
          en: Automatic
          fr: Automatique
        value: auto
      - label:
          en: Always Page Hierarchy
          fr: Toujours la hiérarchie des pages
        value: page
      - label:
          en: Always Manual Links
          fr: Toujours des liens manuels
        value: manual
    default: auto
    description: 
      en: Choose how the navigation links are generated. Automatic -> Uses manual links if added, otherwise falls back to site structure; Always Page Hierarchy -> Only shows links based on your site's structure; Always Manual Links -> Only shows links you add manually.
      fr: Choisissez comment les liens de navigation sont générés. Automatique -> Utilise des liens manuels s'ils sont ajoutés, sinon revient à la structure du site ; Toujours la hiérarchie des pages -> Affiche uniquement les liens basés sur la structure de votre site ; Toujours des liens manuels -> Affiche uniquement les liens
  with_lang_toggle:
    type: boolean
    label: 
      en: Language Toggle
      fr: Basculer la langue
    description: 
      en: Whether or not the language toggle will be displayed in the footer.
      fr: Si oui ou non le basculement de langue sera affiché dans le pied de page.
    default: false

presets:
  with_lang_toggle:
    label:
      en: With Language Toggle
      fr: Avec basculement de langue
    properties:
      with_lang_toggle: true
    image: with_lang_toggle.png